### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by JamesEConnor** [MatthewChatham/glassdoor-review-scraper#30]
I would like to use this repo in a project of mine, but it's missing a license. This unfortunately limits my ability to use it. However, you also indicate that its usable as long as it is cited. Would you be able to add an official license to this repository to reflect that? Thank you very much!

**Comment by JamesEConnor** [comment]
While a license would be preferable, I realized that the disclaimer in the ReadMe seems to legally count as allowing other people to use it.

**Comment by MatthewChatham** [comment]
@JamesEConnor added a license
