### ISSUE TITLE
Missing information on columns pros and cons

### ISSUE THREAD

**Issue by beliakon** [MatthewChatham/glassdoor-review-scraper#34]
Hi all. I was able to run successfully script, but the pros and cons columns is always empty. Do you know what is the reason behind it?

**Comment by beliakon** [comment]
Please see this thread as solution to the topic - https://github.com/MatthewChatham/glassdoor-review-scraper/pull/27

**Comment by sachinchaturvedi93** [comment]
Hi @beliakon check out my forked repo
https://github.com/sachinchaturvedi93/glassdoor-review-scraper/
