### ISSUE TITLE
not finding data on reviews pages

### ISSUE THREAD

**Issue by kiki-data** [MatthewChatham/glassdoor-review-scraper#5]
Everything runs smoothly but it is not finding reviews for each page. It goes to each review page, but then reports 0 reviews found.

**Comment by MatthewChatham** [comment]
@kiki-data did this get resolved?

**Comment by kiki-data** [comment]
Yes, thanks! Problem was on my end.

I'm trying to scrape Hilton, but not getting the output .csv file so now working through that.

**Comment by MatthewChatham** [comment]
Okay great. Please Continue to file issue reports as you encounter them so we can keep the script up to date! Thanks so much!
